<?php

return [
    'admin' => [
        'catalog' => [
            'products' => [
                'booking' => '预定信息',
                'booking-type' => '预定类型',
                'default' => '默认',
                'appointment-booking' => '预定',
                'event-booking' => '活动预定',
                'rental-booking' => '租赁预定',
                'table-booking' => '餐位预定',
                'slot-duration' => '时段 (分钟)',
                'break-time' => '间隔时间 (分钟)',
                'available-every-week' => '每周可用',
                'yes' => '是',
                'no' => '否',
                'available-from' => '有效期从',
                'available-to' => '有效期到',
                'same-slot-all-days' => '每天同一时段',
                'slot-has-quantity' => '时段有',
                'slots' => '时段',
                'from' => '从',
                'to' => '到',
                'qty' => '数量',
                'add-slot' => '创建时段',
                'sunday' => '周日',
                'monday' => '周一',
                'tuesday' => '周二',
                'wednesday' => '周三',
                'thursday' => '周四',
                'friday' => '周五',
                'saturday' => '周六',
                'renting-type' => '租赁类型',
                'daily' => '每天',
                'hourly' => '每小时',
                'daily-hourly' => '(每天 每小时)',
                'daily-price' => '每天价格',
                'hourly-price' => '每小时价格',
                'location' => '定位',
                'show-location' => '显示定位',
                'event-start-date' => '活动开始时间',
                'event-end-date' => '活动结束时间',
                'tickets' => '票',
                'add-ticket' => '创建票',
                'name' => '名称',
                'price' => '价格',
                'quantity' => '数量',
                'description' => '描述',
                'charged-per' => '收费',
                'guest' => '客人',
                'table' => '餐位',
                'prevent-scheduling-before' => '在此之前不做调度计划',
                'guest-limit' => '每个餐位人数限制',
                'guest-capacity' => '客人设备',
                'type' => '类型',
                'many-bookings-for-one-day' => '一天预定多次',
                'one-booking-for-many-days' => '一次预定多天',
                'day' => '天',
                'status' => '状态',
                'open' => '打开',
                'close' => '关闭'
            ]
        ]
    ],

    'shop' => [
        'products' => [
            'location' => '定位',
            'contact' => '联系方式',
            'email' => 'Email',
            'slot-duration' => '时段',
            'slot-duration-in-minutes' => ':minutes 分钟',
            'today-availability' => '今天可用',
            'slots-for-all-days' => '全天演出',
            'sunday' => '周日',
            'monday' => '周一',
            'tuesday' => '周二',
            'wednesday' => '周三',
            'thursday' => '周四',
            'friday' => '周五',
            'saturday' => '周六',
            'closed' => '已关闭',
            'book-an-appointment' => '预约',
            'date' => '日期',
            'slot' => '时段',
            'rent-an-item' => '租赁',
            'choose-rent-option' => '选择租赁选项',
            'daily-basis' => '每天',
            'hourly-basis' => '每小时',
            'select-time-slot'=> '选择时间段',
            'select-slot' => '选择 时段',
            'select-date' => '选择日期',
            'select-rent-time' => '选择租赁时间',
            'from' => '从',
            'to' => '到',
            'book-a-table' => '预定餐位',
            'special-notes' => '特殊说明',
            'event-on' => '活动在',
            'book-your-ticket' => '预定票',
            'per-ticket-price' => '每张票 :price',
            'number-of-tickets' => '票数',
            'total-tickets' => '总票数',
            'base-price' => '基价',
            'total-price' => '总价',
            'base-price-info' => '(适用于每种类型每一张票)'
        ],

        'cart' => [
            'renting_type' => '租赁类型',
            'daily' => '每天',
            'hourly' => '每小时',
            'event-ticket' => '活动入场券',
            'event-from' => '活动从',
            'event-till' => '活动到',
            'rent-type' => '租赁类型',
            'rent-from' => '租赁从',
            'rent-till' => '租赁到',
            'booking-from' => '预定从',
            'booking-till' => '预定到',
            'special-note' => '特殊说明',
        ]
    ]
];
